In [1]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Input Data (Marks):", marks)
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data Type:", marks.dtype)

Input Data (Marks): [78 65 89 56 92]
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int32


In [2]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("Input Data (Marks):", marks)
print("First student's marks:", marks[0])
print("Last student's marks:", marks[-1])
print("Marks of first three students:", marks[:3])
print("Marks of students at even indices:", marks[::2])

Input Data (Marks): [72 85 64 90 76]
First student's marks: 72
Last student's marks: 76
Marks of first three students: [72 85 64]
Marks of students at even indices: [72 64 76]


In [4]:
import numpy as np

data = np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
marks_matrix = data.reshape(5, 3)

print("Input Data (Flat):", data)
print("Reshaped Matrix (5 Students x 3 Subjects):\n", marks_matrix)


Input Data (Flat): [78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]
Reshaped Matrix (5 Students x 3 Subjects):
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [5]:
import numpy as np

internal_marks = np.array([15, 18, 12, 19, 14])
external_marks = np.array([65, 70, 55, 75, 60])
final_marks = internal_marks + external_marks

print("Internal Marks:", internal_marks)
print("External Marks:", external_marks)
print("Final Marks:", final_marks)

Internal Marks: [15 18 12 19 14]
External Marks: [65 70 55 75 60]
Final Marks: [80 88 67 94 74]


In [7]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])
passed_mask = marks >= 50
passed_students = marks[passed_mask]

print("All Marks:", marks)
print("Students scoring 50 or above:", passed_students)

All Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]


In [8]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90], 
    [65, 72, 80], 
    [88, 91, 84], 
    [56, 62, 70], 
    [95, 89, 92]
])

average_marks = np.mean(marks_matrix, axis=1)

print("Marks Matrix:\n", marks_matrix)
print("Average Marks of each student:", average_marks)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average Marks of each student: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [9]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


In [10]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90], 
    [65, 72, 80], 
    [88, 91, 84], 
    [56, 62, 70], 
    [95, 89, 92]
])
subject_totals = np.sum(marks_matrix, axis=0)

print("Marks Matrix:\n", marks_matrix)
print("Total marks obtained in each subject:", subject_totals)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks obtained in each subject: [382 399 416]


In [14]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90], 
    [65, 72, 80], 
    [88, 91, 84], 
    [56, 62, 70], 
    [95, 89, 92]
])

student_totals = np.sum(marks_matrix, axis=1)

print("Marks Matrix:\n", marks_matrix)
print("Total marks obtained by each student:", student_totals)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks obtained by each student: [253 217 263 188 276]


In [ ]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
student_ranks = np.argsort(marks)[::-1] + 1 

print("Original Marks:", marks)
print("Sorted Marks (High to Low):", sorted_marks)
print("Ranking of original students (1st is highest):", student_ranks)

In [15]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])
unique_marks = np.unique(marks)

print("Original Marks:", marks)
print("Unique Marks:", unique_marks)

Original Marks: [85 92 85 76 92]
Unique Marks: [76 85 92]


In [16]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average_mark = np.nanmean(marks)

print("Marks with missing value:", marks)
print("Average Marks (excluding missing):", average_mark)

Marks with missing value: [78. 85. nan 92. 67.]
Average Marks (excluding missing): 80.5


In [17]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])
# np.nanmean ignores np.nan values during calculation
average_mark = np.nanmean(marks)

print("Marks with missing value:", marks)
print("Average Marks (excluding missing):", average_mark)

Marks with missing value: [78. 85. nan 92. 67.]
Average Marks (excluding missing): 80.5


In [18]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])
conditions = [
    marks >= 90,
    (marks >= 75) & (marks < 90),
    (marks >= 60) & (marks < 75),
    marks < 60
]
grades_list = ['A', 'B', 'C', 'F']
grades = np.select(conditions, grades_list)

print("Marks:", marks)
print("Classified Grades:", grades)

Marks: [95 82 74 61 45]
Classified Grades: ['A' 'B' 'C' 'C' 'F']


In [19]:
import numpy as np

random_marks = np.random.randint(0, 101, 5)

print("Generated Random Marks:", random_marks)
print("Total:", np.sum(random_marks))
print("Average:", np.mean(random_marks))
print("Highest:", np.max(random_marks))
print("Lowest:", np.min(random_marks))

Generated Random Marks: [80 37 24 55 69]
Total: 265
Average: 53.0
Highest: 80
Lowest: 24


In [20]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90], 
    [65, 72, 80], 
    [88, 91, 84], 
    [56, 62, 70], 
    [95, 89, 92]
])

# Individual metrics
total_marks = np.sum(marks_matrix, axis=1)
average_marks = np.mean(marks_matrix, axis=1)
highest_marks = np.max(marks_matrix, axis=1)
lowest_marks = np.min(marks_matrix, axis=1)

# Class metrics
class_average = np.mean(marks_matrix)
above_avg_mask = average_marks > class_average
students_above_avg = np.where(above_avg_mask)[0] + 1 

print("Marks Matrix:\n", marks_matrix)
print("Total Marks per Student:", total_marks)
print("Average Marks per Student:", average_marks)
print("Highest Mark per Student:", highest_marks)
print("Lowest Mark per Student:", lowest_marks)
print("Overall Class Average:", round(class_average, 2))
print("Students (1-5) performing above class average:", students_above_avg)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total Marks per Student: [253 217 263 188 276]
Average Marks per Student: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest Mark per Student: [90 80 91 70 95]
Lowest Mark per Student: [78 65 84 56 89]
Overall Class Average: 79.8
Students (1-5) performing above class average: [1 3 5]
